### ISSUE TITLE
Infografía Actividad 4

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-HECTOR-KDM02#1]
[Infografía de proceso por pasos estilo técnico profesional cuadros de colores fondo negro.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-infografia-de-libreria-HECTOR-KDM02/files/14529413/Infografia.de.proceso.por.pasos.estilo.tecnico.profesional.cuadros.de.colores.fondo.negro.pdf)

(INFOGRAFIA)

**Comment by GerardoNR** [comment]
19
información mas detallada, de hay en fuera todo bien.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
